# config/services.yaml

parameters:
    rawg_api_key: '%env(RAWG_API_KEY)%'  # Assurez-vous que cette clé est déclarée correctement ici.

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\RawgApiService:
        arguments:
            $apiKey: '%rawg_api_key%'  # Référence au paramètre ci-dessus.
